#!/usr/bin/env node
/**
 * Download Google Fonts + Material Symbols subset into ./fonts and write css/fonts.css.
 * Re-run when icon set or font weights change.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const fontsDir = join(root, 'fonts');
const outCss = join(root, 'css', 'fonts.css');

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const DISPLAY_CSS_URL =
  'https://fonts.googleapis.com/css2?family=Anybody:ital,wght@0,400;0,700;0,800;0,900;1,400;1,700;1,800;1,900&family=Hanken+Grotesk:wght@400;700&family=JetBrains+Mono:wght@700&display=swap';

const ICON_NAMES = [
  'close',
  'crown',
  'delete',
  'info',
  'menu',
  'menu_book',
  'military_tech',
  'settings',
  'share',
  'sports_kabaddi',
  'volume_off',
  'volume_up',
  'workspace_premium',
];

const ICONS_CSS_URL =
  `https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0..1,0&icon_names=${ICON_NAMES.join(',')}&display=swap`;

/** Keep latin + latin-ext; drop other script subsets to shrink the bundle. */
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

async function fetchText(url) {
  const res = await fetch(url, {
    headers: { 'User-Agent': UA, Accept: 'text/css,*/*;q=0.1' },
  });
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  return res.text();
}

async function fetchBinary(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

function filterCssBySubset(css) {
  const blocks = css.split(/(?=\/\*[^*]*\*\/\s*@font-face)/);
  const kept = [];
  for (const block of blocks) {
    const trimmed = block.trim();
    if (!trimmed) continue;
    const comment = trimmed.match(/^\/\*\s*([^*]+?)\s*\*\//);
    if (comment) {
      const label = comment[1].trim();
      if (!KEEP_SUBSETS.has(label)) continue;
    }
    kept.push(trimmed);
  }
  return kept.join('\n\n') + '\n';
}

function shortName(url, familyHint) {
  const hash = createHash('sha1').update(url).digest('hex').slice(0, 10);
  if (url.includes('anybody')) return `anybody-${hash}.woff2`;
  if (url.includes('hankengrotesk')) return `hanken-grotesk-${hash}.woff2`;
  if (url.includes('jetbrainsmono')) return `jetbrains-mono-${hash}.woff2`;
  if (url.includes('/l/font') || familyHint === 'icons') return `material-symbols-${hash}.woff2`;
  return `font-${hash}.woff2`;
}

async function localizeCss(css, familyHint) {
  const urlMap = new Map();
  const urls = [...css.matchAll(/url\((https:\/\/[^)]+)\)/g)].map((m) => m[1]);
  for (const url of urls) {
    if (urlMap.has(url)) continue;
    const file = shortName(url, familyHint);
    const bytes = await fetchBinary(url);
    writeFileSync(join(fontsDir, file), bytes);
    urlMap.set(url, `../fonts/${file}`);
    console.log(`  ${file} (${(bytes.length / 1024).toFixed(1)} KB)`);
  }
  let out = css;
  for (const [remote, local] of urlMap) {
    out = out.split(remote).join(local);
  }
  return out;
}

mkdirSync(fontsDir, { recursive: true });
mkdirSync(join(root, 'css'), { recursive: true });

console.log('Fetching display fonts CSS…');
const displayRemote = await fetchText(DISPLAY_CSS_URL);
const displayFiltered = filterCssBySubset(displayRemote);
console.log('Downloading display font files…');
const displayLocal = await localizeCss(displayFiltered, 'display');

console.log('Fetching Material Symbols CSS…');
const iconsRemote = await fetchText(ICONS_CSS_URL);
console.log('Downloading icon font…');
const iconsLocal = await localizeCss(iconsRemote, 'icons');

const fontsCss = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand */
${displayLocal}
${iconsLocal}
/* App overrides for filled icons (FILL axis) */
.material-symbols-outlined {
  font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;
}
.material-symbols-outlined.filled {
  font-variation-settings: 'FILL' 1, 'wght' 400, 'GRAD' 0, 'opsz' 24;
}
`;

writeFileSync(outCss, fontsCss);
console.log(`Wrote ${outCss}`);

// Keep app/sw.js font precache entries aligned with downloaded files.
const swPath = join(root, 'app', 'sw.js');
let sw = readFileSync(swPath, 'utf8');
const fontEntries = readdirSync(fontsDir)
  .filter((name) => name.endsWith('.woff2'))
  .sort()
  .map((name) => `  '/fonts/${name}',`)
  .join('\n');
const nextSw = sw.replace(
  /  \/\* fonts:start \*\/[\s\S]*?  \/\* fonts:end \*\//,
  `  /* fonts:start */\n${fontEntries}\n  /* fonts:end */`
);
if (nextSw === sw && !sw.includes('/* fonts:start */')) {
  console.warn('Warning: app/sw.js missing /* fonts:start */ markers; update precache list manually.');
} else {
  writeFileSync(swPath, nextSw);
  console.log(`Updated font precache in ${swPath}`);
}
